#!/usr/bin/env bash
# workspace.sh — the whole harness in one script.
#   ./workspace.sh setup              one-time: wire the safety hook, print what to do next
#   ./workspace.sh clone              rebuild the fleet from catalog/repos.yaml
#   ./workspace.sh snapshot <task>    pin every child's commit into snapshots/<date>-<task>.lock.yaml
#   ./workspace.sh restore <lockfile> check children back out to a lockfile's SHAs
#   ./workspace.sh check              verify manifest + cited lockfiles (session-init / pre-commit)
# Plain bash (macOS 3.2 ok), zero dependencies.
set -u
cd "$(dirname "$0")" || exit 1
MANIFEST="catalog/repos.yaml"
tmp=""; trap 'rm -f "$tmp"' EXIT

entries() { # one line per repo: id|path|remote|branch|access
  awk '
    function flush() { if (id != "") print id "|" path "|" remote "|" branch "|" access }
    /^- id:/                       { flush(); id=$3; path=""; remote=""; branch=""; access="" }
    /^[[:space:]]+path:/           { path=$2 }
    /^[[:space:]]+remote:/         { remote=$2 }
    /^[[:space:]]+default_branch:/ { branch=$2 }
    /^[[:space:]]+access:/         { access=$2 }
    END                            { flush() }
  ' "$MANIFEST"
}

cmd="${1:-help}"
case "$cmd" in clone|snapshot|check)
  [ -f "$MANIFEST" ] || { echo "FAIL: $MANIFEST missing" >&2; exit 1; }
esac

case "$cmd" in

setup)
  git config core.hooksPath .githooks
  echo "safety hook wired: every commit now runs './workspace.sh check' first."
  bash "$0" check || true
  echo
  echo "next steps:"
  if grep -qE '^- id:' "$MANIFEST" 2>/dev/null; then
    echo "  1. ./workspace.sh clone            # fleet appears under projects/"
  else
    echo "  1. edit catalog/repos.yaml         # declare your child repos + access levels"
    echo "  2. ./workspace.sh clone            # fleet appears under projects/"
  fi
  git remote | grep -q . \
    || echo "  •  add a PRIVATE remote for this repo and push — its memory must survive a dead disk"
  ;;

clone)
  tmp="$(mktemp)"; entries > "$tmp"
  if [ ! -s "$tmp" ]; then
    echo "nothing to clone yet — add your repos to catalog/repos.yaml first."
    exit 0
  fi
  fail=0
  while IFS='|' read -r id path remote branch access; do
    [ -n "$id" ] || continue
    if [ -d "$path/.git" ]; then echo "[$id] already cloned"; else
      echo "[$id] cloning $remote → $path"
      git clone --quiet --branch "$branch" "$remote" "$path" \
        || { echo "[$id] CLONE FAILED — continuing with the rest" >&2; fail=$((fail+1)); continue; }
    fi
    if [ "$access" = "read-only" ]; then
      git -C "$path" remote set-url --push origin DISALLOWED_READ_ONLY
      echo "[$id] read-only → push disabled"
    elif [ "$(git -C "$path" remote get-url --push origin 2>/dev/null)" = "DISALLOWED_READ_ONLY" ]; then
      git -C "$path" remote set-url --push origin "$remote"
      echo "[$id] access upgraded → push re-enabled"
    fi
  done < "$tmp"
  [ "$fail" -eq 0 ] && echo "fleet complete." || { echo "$fail repo(s) failed to clone." >&2; exit 1; }
  ;;

snapshot)
  task="${2:?usage: workspace.sh snapshot <task>}"
  case "$task" in
    */*|*" "*) echo "task name must not contain '/' or spaces" >&2; exit 1 ;;
  esac
  tmp="$(mktemp)"; entries > "$tmp"
  [ -s "$tmp" ] || { echo "manifest has no repos — edit catalog/repos.yaml first" >&2; exit 1; }
  out="snapshots/$(date +%F)-${task}.lock.yaml"
  if [ -f "$out" ]; then
    echo "[$out] already exists — lockfiles are cited evidence; pick another task name or delete it deliberately" >&2
    exit 1
  fi
  mkdir -p snapshots
  { echo "# GENERATED by workspace.sh snapshot — do not hand-edit."
    echo "task: $task"; echo "created: $(date +%F)"; echo "repos:"; } > "$out" || exit 1
  while IFS='|' read -r id path remote branch access; do
    [ -n "$id" ] || continue
    [ -d "$path/.git" ] || { echo "[$id] not cloned — run ./workspace.sh clone" >&2; rm -f "$out"; exit 1; }
    { echo "  - id: $id"
      echo "    path: $path"
      echo "    sha: $(git -C "$path" rev-parse HEAD)"
      echo "    branch: $(git -C "$path" rev-parse --abbrev-ref HEAD)"
      echo "    dirty: $(git -C "$path" status --porcelain | wc -l | tr -d ' ')"; } >> "$out"
  done < "$tmp"
  echo "wrote $out"
  ;;

restore)
  lock="${2:?usage: workspace.sh restore <lockfile>}"
  [ -f "$lock" ] || { echo "no such lockfile: $lock" >&2; exit 1; }
  tmp="$(mktemp)"
  awk '
    /^[[:space:]]+- id:/ { if (path != "") print path "|" sha; path=""; sha="" }
    /^[[:space:]]+path:/ { path=$2 }
    /^[[:space:]]+sha:/  { sha=$2 }
    END                  { if (path != "") print path "|" sha }
  ' "$lock" > "$tmp"
  fail=0
  while IFS='|' read -r path sha; do
    [ -n "$path" ] || continue
    [ -d "$path/.git" ] || { echo "[$path] not cloned — skipped" >&2; fail=$((fail+1)); continue; }
    if [ -n "$(git -C "$path" status --porcelain)" ]; then
      echo "[$path] has local changes — NOT touching it" >&2; fail=$((fail+1)); continue
    fi
    git -C "$path" checkout --quiet --detach "$sha" && echo "[$path] → $sha" \
      || { echo "[$path] RESTORE FAILED (sha $sha unreachable — history rewritten upstream?)" >&2; fail=$((fail+1)); }
  done < "$tmp"
  [ "$fail" -eq 0 ] || { echo "restore: $fail repo(s) not restored." >&2; exit 1; }
  ;;

check)
  status=0; n=0; tmp="$(mktemp)"; entries > "$tmp"
  while IFS='|' read -r id path remote branch access; do
    n=$((n+1))
    [ -n "$id" ] && [ -n "$path" ] && [ -n "$remote" ] && [ -n "$branch" ] \
      || { echo "FAIL: manifest entry $n incomplete (needs id/path/remote/default_branch)" >&2; status=1; }
    case "$access" in write|pr-only|read-only) : ;;
      *) echo "FAIL: [$id] access must be write|pr-only|read-only (got '${access:-<empty>}')" >&2; status=1 ;; esac
  done < "$tmp"
  raw="$(grep -cE '^[[:space:]]*-[[:space:]]*id:' "$MANIFEST" || true)"
  if [ "$raw" -gt "$n" ]; then
    echo "FAIL: manifest has $raw 'id:' line(s) but only $n parse — check indentation ('- id:' must start at column 0)" >&2
    status=1
  fi
  bad="$(awk '
    /^[[:space:]]*#/ { next }
    /^- id:/ { if (NF > 3) print NR; next }
    /^[[:space:]]+(path|remote|default_branch|access):/ { if (NF > 2) print NR }
  ' "$MANIFEST")"
  [ -z "$bad" ] || { echo "FAIL: manifest line(s) $(echo $bad | tr ' ' ','): values must be single tokens (no spaces or inline comments)" >&2; status=1; }
  [ "$n" -gt 0 ] || echo "warn: manifest has no repos yet — edit catalog/repos.yaml"
  refs="$(grep -rhE '^snapshot:' tasks docs 2>/dev/null | awk '{print $2}' | sort -u)"
  for ref in $refs; do
    case "$ref" in *"<"*) continue ;; esac
    [ -f "$ref" ] || { echo "FAIL: cited lockfile missing: $ref" >&2; status=1; }
  done
  newest="$(ls .agents/memory/sessions 2>/dev/null | grep -E '^[0-9]{4}-' | sort | tail -1)"
  echo "info: newest session log: ${newest:-none yet}"
  [ "$status" -eq 0 ] && echo "check: PASS ($n repo(s) in manifest)" || echo "check: FAIL" >&2
  exit "$status"
  ;;

*)
  sed -n '2,7p' "$0"
  ;;
esac
